[SDCcc]
CIMode=true
GraphicalPopups=true

[SDCcc.TLS]
FileDirectory="C:/Users/pilzmaxi/Documents/dev/certs"
KeyStorePassword="whatever"
TrustStorePassword="whatever"
ParticipantPrivatePassword="dummypass"
EnabledProtocols = ["TLSv1.2", "TLSv1.3"]

[SDCcc.Network]
InterfaceAddress="192.168.2.107"

[SDCcc.Consumer]
Enable=true
DeviceEpr="urn:uuid:9e823ba0-1292-4482-93ad-f60547c79c5a"

[SDCcc.Provider]
Enable=false

[SDCcc.gRPC]
ServerAddress="localhost:50051"